apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
  labels:
    app: account-service
spec:
  replicas: 1 # Number of replicas that will be created for this deployment
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: localhost:5000/account-service:0.1 # Image that will be used inside the container in the cluster
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8091 # The port that the container is running on in the cluster
---
apiVersion: v1
kind: Service
metadata:
  name: account-service-service
spec:
  type: LoadBalancer # type of the service
  selector:
    app: account-service
  ports:
  - protocol: TCP
    port: 8091 # The port that the service is running on in the cluster
    targetPort: 8091 # The port exposed by the service