apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-deployment
  labels:
    app: customer-service
spec:
  replicas: 1 # Number of replicas that will be created for this deployment
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service
        image: localhost:5000/customer-service:0.1 # Image that will be used inside the container in the cluster
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8092 # The port that the container is running on in the cluster
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service-service
spec:
  type: LoadBalancer # type of the service
  selector:
    app: customer-service
  ports:
  - protocol: TCP
    port: 8092 # The port that the service is running on in the cluster
    targetPort: 8092 # The port exposed by the service